### ISSUE TITLE
missing package "github.com/apache/iotdb-client-go/common"

### ISSUE THREAD

**Issue by yz3358** [apache/iotdb-client-go#106]
I've tried to follow the session_example, but it seems the module "github.com/apache/iotdb-client-go@latest" does not contain a pkg named "common"

**Comment by HTHou** [comment]
If you are using latest release, which should be https://github.com/apache/iotdb-client-go/tree/v1.3.2, you should refer to https://github.com/apache/iotdb-client-go/blob/v1.3.2/example/session_pool/session_pool_example.go.

The main branch has updated the package structure.
