### ISSUE TITLE
go compile error

### ISSUE THREAD

**Issue by bodypumper** [apache/iotdb-client-go#32]
go version：1.18.1
demo problem views

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/44149782/169945408-2605ec9b-2494-4c0b-bf7a-881d5aaefb82.png">

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/44149782/169945584-f66877f5-9338-4b83-a1be-ea2e7fba7e5b.png">

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/44149782/169945626-dcb39b1c-8ef6-461a-bc24-a4b13fc0b676.png">

**Comment by jixuan1989** [comment]
Hi, could you report your iotdb server version?

**Comment by bodypumper** [comment]
> Hi, could you report your iotdb server version?



> Hi, could you report your iotdb server version?

In go mod , iotdb server version is v0.12.0.
i try to go get new version , but the ‘v0.12.0’ is latest.
