### ISSUE TITLE
 assignment mismatch: 2 variables but thrift.NewTSocketConf returns 1 value

### ISSUE THREAD

**Issue by Lay523** [apache/iotdb-client-go#52]
version:v0.13.0

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/94181680/195238516-acb41141-f14c-43b4-ba16-7d8f322ca8cf.png">

<img width="914" alt="image" src="https://user-images.githubusercontent.com/94181680/195238553-22e5802c-c496-4680-bae0-bfb47a2f60b0.png">

**Comment by citrusreticulata** [comment]
Please check the version of thrift and the version of iotdb-clinet-go.
In thrift 0.14.1, function `NewTSocketConf` returns 2 values. It's specific implementation of this function is as follows:
```
func NewTSocketConf(hostPort string, conf *TConfiguration) (*TSocket, error) {
    addr, err := net.ResolveTCPAddr("tcp", hostPort)
    if err != nil {
        return nil, err
    }
    return NewTSocketFromAddrConf(addr, conf), nil
}
```
In thrift 0.15.0, function `NewTSocketConf` returns 1 value. It's specific implementation of this function is as follows:
```
func NewTSocketConf(hostPort string, conf *TConfiguration) *TSocket {
    return NewTSocketFromAddrConf(tcpAddr(hostPort), conf)
}
```

**Comment by citrusreticulata** [comment]
Has this issue been solved? If this issue has been solved, it can be closed.
