### ISSUE TITLE
写入丢包

### ISSUE THREAD

**Issue by hnhkj** [apache/iotdb-client-go#90]
我需要连续写入数据到数据库中，但是发现中间一直有丢包现象。通过调用insertWbRawData(v.Payload, i)函数，checkError()没有返回错误信息。但是检查数据库确没有发现数据。

```
func insertWbRawData(val string, cnt int) {
	var (
		deviceId           = "root.call4.care.wbs.raw"
		measurements       = []string{"data", "cnt"}
		values             = []string{}
		timestamp    int64 = time.Now().UTC().UnixNano() / 1000000
	)
	values = append(values, val+" "+strconv.Itoa(cnt))
	values = append(values, strconv.Itoa(cnt))
	checkError(session.InsertStringRecord(deviceId, measurements, values, timestamp))
}

func checkError(status *rpc.TSStatus, err error) {
	if err != nil {
		log.Fatal(err)
	}

	if status != nil {
		if err = client.VerifySuccess(status); err != nil {
			log.Println(err)
		} else {
			fmt.Println("suc", i)
		}
	}
}
```

**Comment by HTHou** [comment]
是一条数据都没有还是部分没有。如果是数据的 count 值对不上，有可能是两次写入的timestamp相同导致的。

**Comment by hnhkj** [comment]
部分丢包，每一个包的cnt是不同的，cnt运行一次递增1。其它值有可能相同。

**Comment by HTHou** [comment]
如果同一个序列两次写入的 timestamp 相同，iotdb 的特性是会覆盖上一个写入的值，相当于 update。这样的话 count 值会比写入的次数少。

**Comment by hnhkj** [comment]
如果保留所有数据，即使timestamp相同？

**Comment by HTHou** [comment]
timestamp相同的两个值，只能考虑是当两个时间序列来存，因为timestamp 对于一条时间序列是主键，同一个timestamp没办法对应多个值。

**Comment by hnhkj** [comment]
时间戳单位是ms还是s?

**Comment by HTHou** [comment]
> 时间戳单位是ms还是s?

https://iotdb.apache.org/zh/UserGuide/V1.1.x/Reference/Common-Config-Manual.html#%E7%B3%BB%E7%BB%9F%E9%85%8D%E7%BD%AE%E9%A1%B9 默认是ms
